import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: 'white',
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    alignItems: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    marginVertical: 24,
    color: '#212529',
    letterSpacing: 0.5,
  },
  // QR Kod Tara Butonu Stilleri
  scanButton: {
    width: '100%',
    backgroundColor: '#3B82F6',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  scanButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  optionsContainer: {
    width: '100%',
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
    color: '#212529',
    letterSpacing: 0.3,
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  optionButton: {
    width: '48%',
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#fff',
    marginBottom: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  selectedOption: {
    backgroundColor: '#3B82F6',
    borderColor: '#3B82F6',
  },
  optionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#495057',
  },
  selectedOptionText: {
    color: '#fff',
  },
  inputContainer: {
    width: '100%',
    marginBottom: 24,
  },
  input: {
    width: '100%',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    fontSize: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  generateButton: {
    backgroundColor: '#3B82F6',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonDisabled: {
    backgroundColor: '#ADB5BD',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  qrContainer: {
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 24,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
    marginTop: 16,
    marginBottom: 24,
    width: '100%',
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  qrInfo: {
    marginTop: 16,
    fontSize: 15,
    color: '#495057',
    fontWeight: '500',
  },
  // Kamera ve Modal Stilleri
  modalContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  cameraContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  scanFrame: {
    width: 280,
    height: 280,
    borderWidth: 3,
    borderColor: '#fff',
    borderRadius: 16,
    backgroundColor: 'transparent',
  },
  modalButtons: {
    flexDirection: 'row',
    padding: 24,
    justifyContent: 'space-between',
  },
  modalButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#343A40',
    margin: 8,
    alignItems: 'center',
  },
  galleryButton: {
    backgroundColor: '#3B82F6',
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  modalText: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
    padding: 24,
    fontWeight: '600',
  },
  barcodeCaption: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 12,
    color: '#495057',
  },
  downloadButton: {
    backgroundColor: '#3B82F6',
    padding: 14,
    borderRadius: 12,
    marginTop: 20,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  downloadButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  gradientToggle: {
    backgroundColor: '#E9ECEF',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradientActive: {
    backgroundColor: '#3B82F6',
  },
  gradientToggleText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#495057',
  },
  gradientActiveText: {
    color: '#fff',
  },
  colorSchemeButton: {
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    marginRight: 10,
    borderWidth: 2,
    borderColor: 'transparent',
    width: 100,
  },
  colorPreview: {
    width: 40,
    height: 40,
    borderRadius: 8,
    marginBottom: 8,
  },
  colorSchemeName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#495057',
    textAlign: 'center',
  },
  designOption: {
    backgroundColor: '#E9ECEF',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  designOptionActive: {
    backgroundColor: '#3B82F6',
  },
  designOptionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#495057',
  },
  designOptionActiveText: {
    color: '#fff',
  },
  designOptionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  designOptionButton: {
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    backgroundColor: '#fff',
    flex: 1,
  },
  designOptionButtonActive: {
    borderColor: '#3B82F6',
  },
  designOptionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#495057',
    marginTop: 4,
  },
  optionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#495057',
    marginBottom: 8,
  },
  imageModalContainer: {
    flex: 1,
    backgroundColor: '#000',
    padding: 16,
    justifyContent: 'space-between',
  },
  imageModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginTop: 20,
    marginBottom: 20,
    textAlign: 'center',
  },
  selectedImageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#222',
    borderRadius: 12,
    padding: 10,
    marginBottom: 20,
    overflow: 'hidden',
  },
  selectedImage: {
    width: '90%',
    height: '70%',
    borderRadius: 8,
  },
  imageInstructions: {
    fontSize: 14,
    fontWeight: '500',
    color: '#fff',
    textAlign: 'center',
    marginTop: 20,
    paddingHorizontal: 16,
  },
  noImageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#222',
    borderRadius: 12,
    marginBottom: 20,
  },
  noImageText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#aaa',
  },
  imageModalButtons: {
    flexDirection: 'row',
    paddingVertical: 16,
    justifyContent: 'space-between',
  },
}); 